Return-Path: <kvm-ppc-owner@vger.kernel.org>
X-Original-To: lists+kvm-ppc@lfdr.de
Delivered-To: lists+kvm-ppc@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id B9B2A3512B2
	for <lists+kvm-ppc@lfdr.de>; Thu,  1 Apr 2021 11:48:52 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S233637AbhDAJsV (ORCPT <rfc822;lists+kvm-ppc@lfdr.de>);
        Thu, 1 Apr 2021 05:48:21 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:42228 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S232585AbhDAJr4 (ORCPT
        <rfc822;kvm-ppc@vger.kernel.org>); Thu, 1 Apr 2021 05:47:56 -0400
Received: from mail-pf1-x42f.google.com (mail-pf1-x42f.google.com [IPv6:2607:f8b0:4864:20::42f])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 13629C0613E6
        for <kvm-ppc@vger.kernel.org>; Thu,  1 Apr 2021 02:47:56 -0700 (PDT)
Received: by mail-pf1-x42f.google.com with SMTP id x126so1044045pfc.13
        for <kvm-ppc@vger.kernel.org>; Thu, 01 Apr 2021 02:47:56 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=date:from:subject:to:cc:references:in-reply-to:mime-version
         :message-id:content-transfer-encoding;
        bh=e28mP4vqW0wK0RDVgiCQ9UNycWD3MSCRgzIo6Rq/6EE=;
        b=r8PmL1JInEYuHXsXziEAl4FhtQ8tkm5YYezN1iNK5USe1peYsO5pAm/JfujCotTziZ
         caItmqZEM77iVQAhb23OiUA9AZZkaeOrOCh/MWjSVkmZDQgB+CvzYfO433X5ggtfiMQf
         NIGv+sfgiHJ1PrpidFSEB/rnFKG8QWoL25bya+lcXhPZOizyQM6ATdqb3FmfMlSav8sG
         97KveMpQhPCOcF2qLsigKfgpWHniO5WqOSsL1jT9aCVAAotDPIeGs3nRuU4c3lZzlNf6
         qzJxTcpz4l11hXEbkXECesLXgr50mBN/tk+445gLEQ28DnO1JUlpDvaUFgXQDq0RwEQG
         KK1Q==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:date:from:subject:to:cc:references:in-reply-to
         :mime-version:message-id:content-transfer-encoding;
        bh=e28mP4vqW0wK0RDVgiCQ9UNycWD3MSCRgzIo6Rq/6EE=;
        b=F9TRJUuTt04zoOsu89HCNoUVfIMgiIeXvGFqvHQavANUtSKPLABa3C6JlYUj43acGI
         E5JTzaJPbBabxFUIWLtrq8Ih1Npnuqp6NfCVN+ORLc3FX5uzr3Uz9UaYvWWhX94aoBs2
         NDHM95q2oX2PWMSV9K9MR5JuRC/0Y6Py86reVuu7AUzYvMgRv2XCK289kJZpeDeubDuk
         U+8bOMoYNTRO8y3SzL1CUxqBEc654RCzN+OU+XnRBaAMhlRtXvImQf4xGbou7Dgf38Ol
         aWm/ezTgMfa06m+UIGOXL4IwFet4SNgAPHy/JAAwG0ICAz3x+ANuO+9HiPomiih3qRV3
         +NaA==
X-Gm-Message-State: AOAM532ogu2nqe21ZmR8QCEoAEmhMxfyYPP4M4hsHtIq+HyyuF4vi1GL
        HE9u/J0xBTE84qzVyPaXtjQS8Mc7UnHnRA==
X-Google-Smtp-Source: ABdhPJz+WaoWgQlCxrZ2aX6kZeOc8PjTx0Uv4z/wkSQMW/gQi0ep/6WO1H8Hi0ezqCZrQ9b0AeHMpw==
X-Received: by 2002:a65:6483:: with SMTP id e3mr6858076pgv.208.1617270475657;
        Thu, 01 Apr 2021 02:47:55 -0700 (PDT)
Received: from localhost ([1.128.222.172])
        by smtp.gmail.com with ESMTPSA id ch15sm4703580pjb.46.2021.04.01.02.47.54
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Thu, 01 Apr 2021 02:47:55 -0700 (PDT)
Date:   Thu, 01 Apr 2021 19:47:49 +1000
From:   Nicholas Piggin <npiggin@gmail.com>
Subject: Re: [PATCH v4 09/46] powerpc/64s: remove KVM SKIP test from
 instruction breakpoint handler
To:     Paul Mackerras <paulus@ozlabs.org>
Cc:     Daniel Axtens <dja@axtens.net>,
        Fabiano Rosas <farosas@linux.ibm.com>, kvm-ppc@vger.kernel.org,
        linuxppc-dev@lists.ozlabs.org
References: <20210323010305.1045293-1-npiggin@gmail.com>
        <20210323010305.1045293-10-npiggin@gmail.com>
        <YGQAfCOAR5Hfj13u@thinks.paulus.ozlabs.org>
In-Reply-To: <YGQAfCOAR5Hfj13u@thinks.paulus.ozlabs.org>
MIME-Version: 1.0
Message-Id: <1617270447.zkb024siva.astroid@bobo.none>
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Precedence: bulk
List-ID: <kvm-ppc.vger.kernel.org>
X-Mailing-List: kvm-ppc@vger.kernel.org

Excerpts from Paul Mackerras's message of March 31, 2021 2:54 pm:
> On Tue, Mar 23, 2021 at 11:02:28AM +1000, Nicholas Piggin wrote:
>> The code being executed in KVM_GUEST_MODE_SKIP is hypervisor code with
>> MSR[IR]=3D0, so the faults of concern are the d-side ones caused by acce=
ss
>> to guest context by the hypervisor.
>>=20
>> Instruction breakpoint interrupts are not a concern here. It's unlikely
>> any good would come of causing breaks in this code, but skipping the
>> instruction that caused it won't help matters (e.g., skip the mtmsr that
>> sets MSR[DR]=3D0 or clears KVM_GUEST_MODE_SKIP).
>>=20
>> Reviewed-by: Daniel Axtens <dja@axtens.net>
>> Reviewed-by: Fabiano Rosas <farosas@linux.ibm.com>
>> Signed-off-by: Nicholas Piggin <npiggin@gmail.com>
>=20
> It might be worth noting in the commit message that the 0x1300
> interrupt was dropped from the architecture a long time ago and is not
> generated by P7, P8, P9 or P10.

Good background, I'll add that.

Thanks,
Nick

>=20
> Acked-by: Paul Mackerras <paulus@ozlabs.org>
>=20
